
[[constraint]]
  branch = "master"
  name = "github.com/avast/apkparser"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/bitrise"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-android"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-xcode"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/xcode-project"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-steplib/steps-xcode-test"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  branch = "master"
  name = "howett.net/plist"

[prune]
  go-tests = true
  unused-packages = true
